// Code generated by entc, DO NOT EDIT.

package linuseridentiy

const (
	// Label holds the string label denoting the linuseridentiy type in the database.
	Label = "lin_user_identiy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldIdentityType holds the string denoting the identity_type field in the database.
	FieldIdentityType = "identity_type"
	// FieldIdentifier holds the string denoting the identifier field in the database.
	FieldIdentifier = "identifier"
	// FieldCredential holds the string denoting the credential field in the database.
	FieldCredential = "credential"
	// Table holds the table name of the linuseridentiy in the database.
	Table = "lin_user_identiy"
)

// Columns holds all SQL columns for linuseridentiy fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldIdentityType,
	FieldIdentifier,
	FieldCredential,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "lin_user_identiy"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"lin_user_lin_user_identiy",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
