// Code generated by entc, DO NOT EDIT.

package lingrouppermission

const (
	// Label holds the string label denoting the lingrouppermission type in the database.
	Label = "lin_group_permission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldPermissionID holds the string denoting the permission_id field in the database.
	FieldPermissionID = "permission_id"
	// Table holds the table name of the lingrouppermission in the database.
	Table = "lin_group_permission"
)

// Columns holds all SQL columns for lingrouppermission fields.
var Columns = []string{
	FieldID,
	FieldGroupID,
	FieldPermissionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
