// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLesson = "lesson"

// Lesson mapped from table <lesson>
type Lesson struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TeacherID    int64          `gorm:"column:teacher_id;not null" json:"teacher_id"`
	Title        string         `gorm:"column:title;not null;comment:标题" json:"title"`                                    // 标题
	Introduce    string         `gorm:"column:introduce;not null;comment:简介" json:"introduce"`                            // 简介
	StartAt      time.Time      `gorm:"column:start_at;comment:上课时间" json:"start_at"`                                     // 上课时间
	EndAt        time.Time      `gorm:"column:end_at;comment:上课时间" json:"end_at"`                                         // 上课时间
	LessonStatus int32          `gorm:"column:lesson_status;not null;comment:状态 0 未开始 1 正在上课 2 已结束" json:"lesson_status"` // 状态 0 未开始 1 正在上课 2 已结束
	IsPaid       int32          `gorm:"column:is_paid;not null;comment:类型 0 免费 1 收费" json:"is_paid"`                      // 类型 0 免费 1 收费
	Price        float64        `gorm:"column:price;not null;default:0.00;comment:价格" json:"price"`                       // 价格
	Province     string         `gorm:"column:province;not null;comment:省" json:"province"`                               // 省
	City         string         `gorm:"column:city;not null;comment:市" json:"city"`                                       // 市
	Area         string         `gorm:"column:area;not null;comment:区" json:"area"`                                       // 区
	Address      string         `gorm:"column:address;not null;comment:地址" json:"address"`                                // 地址
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Lesson's table name
func (*Lesson) TableName() string {
	return TableNameLesson
}
