// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLessonComment = "lesson_comment"

// LessonComment mapped from table <lesson_comment>
type LessonComment struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64          `gorm:"column:user_id;not null" json:"user_id"`
	TeacherID int64          `gorm:"column:teacher_id;not null" json:"teacher_id"`
	LessonID  int64          `gorm:"column:lesson_id;not null" json:"lesson_id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName LessonComment's table name
func (*LessonComment) TableName() string {
	return TableNameLessonComment
}
