// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLinFile = "lin_file"

// LinFile mapped from table <lin_file>
type LinFile struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Path      string         `gorm:"column:path;not null" json:"path"`
	Type      int32          `gorm:"column:type;not null;default:1;comment:1 LOCAL 本地，2 REMOTE 远程" json:"type"` // 1 LOCAL 本地，2 REMOTE 远程
	Name      string         `gorm:"column:name;not null" json:"name"`
	Extension string         `gorm:"column:extension" json:"extension"`
	Size      int32          `gorm:"column:size" json:"size"`
	Md5       string         `gorm:"column:md5;comment:md5值，防止上传重复文件" json:"md5"` // md5值，防止上传重复文件
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName LinFile's table name
func (*LinFile) TableName() string {
	return TableNameLinFile
}
