// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLinUserGroup = "lin_user_group"

// LinUserGroup mapped from table <lin_user_group>
type LinUserGroup struct {
	ID      int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID  int64 `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`   // 用户id
	GroupID int64 `gorm:"column:group_id;not null;comment:分组id" json:"group_id"` // 分组id
}

// TableName LinUserGroup's table name
func (*LinUserGroup) TableName() string {
	return TableNameLinUserGroup
}
