// Code generated by entc, DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"lin-cms-go/internal/data/model/linfile"
	"lin-cms-go/internal/data/model/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinFileDelete is the builder for deleting a LinFile entity.
type LinFileDelete struct {
	config
	hooks    []Hook
	mutation *LinFileMutation
}

// Where appends a list predicates to the LinFileDelete builder.
func (lfd *LinFileDelete) Where(ps ...predicate.LinFile) *LinFileDelete {
	lfd.mutation.Where(ps...)
	return lfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lfd *LinFileDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lfd.hooks) == 0 {
		affected, err = lfd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LinFileMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lfd.mutation = mutation
			affected, err = lfd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lfd.hooks) - 1; i >= 0; i-- {
			if lfd.hooks[i] == nil {
				return 0, fmt.Errorf("model: uninitialized hook (forgotten import model/runtime?)")
			}
			mut = lfd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lfd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lfd *LinFileDelete) ExecX(ctx context.Context) int {
	n, err := lfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lfd *LinFileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: linfile.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: linfile.FieldID,
			},
		},
	}
	if ps := lfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, lfd.driver, _spec)
}

// LinFileDeleteOne is the builder for deleting a single LinFile entity.
type LinFileDeleteOne struct {
	lfd *LinFileDelete
}

// Exec executes the deletion query.
func (lfdo *LinFileDeleteOne) Exec(ctx context.Context) error {
	n, err := lfdo.lfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{linfile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lfdo *LinFileDeleteOne) ExecX(ctx context.Context) {
	lfdo.lfd.ExecX(ctx)
}
