// Code generated by entc, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"
	"lin-cms-go/internal/data/model/linlog"
	"lin-cms-go/internal/data/model/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinLogQuery is the builder for querying LinLog entities.
type LinLogQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LinLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LinLogQuery builder.
func (llq *LinLogQuery) Where(ps ...predicate.LinLog) *LinLogQuery {
	llq.predicates = append(llq.predicates, ps...)
	return llq
}

// Limit adds a limit step to the query.
func (llq *LinLogQuery) Limit(limit int) *LinLogQuery {
	llq.limit = &limit
	return llq
}

// Offset adds an offset step to the query.
func (llq *LinLogQuery) Offset(offset int) *LinLogQuery {
	llq.offset = &offset
	return llq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (llq *LinLogQuery) Unique(unique bool) *LinLogQuery {
	llq.unique = &unique
	return llq
}

// Order adds an order step to the query.
func (llq *LinLogQuery) Order(o ...OrderFunc) *LinLogQuery {
	llq.order = append(llq.order, o...)
	return llq
}

// First returns the first LinLog entity from the query.
// Returns a *NotFoundError when no LinLog was found.
func (llq *LinLogQuery) First(ctx context.Context) (*LinLog, error) {
	nodes, err := llq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{linlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (llq *LinLogQuery) FirstX(ctx context.Context) *LinLog {
	node, err := llq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LinLog ID from the query.
// Returns a *NotFoundError when no LinLog ID was found.
func (llq *LinLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = llq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{linlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (llq *LinLogQuery) FirstIDX(ctx context.Context) int {
	id, err := llq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Last returns the last LinLog entity from the query.
// Returns a *NotFoundError when no LinLog was found.
func (llq *LinLogQuery) Last(ctx context.Context) (*LinLog, error) {
	nodes, err := llq.All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{linlog.Label}
	}
	return nodes[len(nodes)-1], nil
}

// LastX is like Last, but panics if an error occurs.
func (llq *LinLogQuery) LastX(ctx context.Context) *LinLog {
	node, err := llq.Last(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// LastID returns the last LinLog ID from the query.
// Returns a *NotFoundError when no LinLog ID was found.
func (llq *LinLogQuery) LastID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = llq.IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{linlog.Label}
		return
	}
	return ids[len(ids)-1], nil
}

// LastIDX is like LastID, but panics if an error occurs.
func (llq *LinLogQuery) LastIDX(ctx context.Context) int {
	id, err := llq.LastID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LinLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one LinLog entity is not found.
// Returns a *NotFoundError when no LinLog entities are found.
func (llq *LinLogQuery) Only(ctx context.Context) (*LinLog, error) {
	nodes, err := llq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{linlog.Label}
	default:
		return nil, &NotSingularError{linlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (llq *LinLogQuery) OnlyX(ctx context.Context) *LinLog {
	node, err := llq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LinLog ID in the query.
// Returns a *NotSingularError when exactly one LinLog ID is not found.
// Returns a *NotFoundError when no entities are found.
func (llq *LinLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = llq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{linlog.Label}
	default:
		err = &NotSingularError{linlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (llq *LinLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := llq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LinLogs.
func (llq *LinLogQuery) All(ctx context.Context) ([]*LinLog, error) {
	if err := llq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return llq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (llq *LinLogQuery) AllX(ctx context.Context) []*LinLog {
	nodes, err := llq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LinLog IDs.
func (llq *LinLogQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := llq.Select(linlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (llq *LinLogQuery) IDsX(ctx context.Context) []int {
	ids, err := llq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (llq *LinLogQuery) Count(ctx context.Context) (int, error) {
	if err := llq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return llq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (llq *LinLogQuery) CountX(ctx context.Context) int {
	count, err := llq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (llq *LinLogQuery) Exist(ctx context.Context) (bool, error) {
	if err := llq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return llq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (llq *LinLogQuery) ExistX(ctx context.Context) bool {
	exist, err := llq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LinLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (llq *LinLogQuery) Clone() *LinLogQuery {
	if llq == nil {
		return nil
	}
	return &LinLogQuery{
		config:     llq.config,
		limit:      llq.limit,
		offset:     llq.offset,
		order:      append([]OrderFunc{}, llq.order...),
		predicates: append([]predicate.LinLog{}, llq.predicates...),
		// clone intermediate query.
		sql:  llq.sql.Clone(),
		path: llq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LinLog.Query().
//		GroupBy(linlog.FieldCreateTime).
//		Aggregate(model.Count()).
//		Scan(ctx, &v)
//
func (llq *LinLogQuery) GroupBy(field string, fields ...string) *LinLogGroupBy {
	group := &LinLogGroupBy{config: llq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := llq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return llq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.LinLog.Query().
//		Select(linlog.FieldCreateTime).
//		Scan(ctx, &v)
//
func (llq *LinLogQuery) Select(fields ...string) *LinLogSelect {
	llq.fields = append(llq.fields, fields...)
	return &LinLogSelect{LinLogQuery: llq}
}

func (llq *LinLogQuery) prepareQuery(ctx context.Context) error {
	for _, f := range llq.fields {
		if !linlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("model: invalid field %q for query", f)}
		}
	}
	if llq.path != nil {
		prev, err := llq.path(ctx)
		if err != nil {
			return err
		}
		llq.sql = prev
	}
	return nil
}

func (llq *LinLogQuery) sqlAll(ctx context.Context) ([]*LinLog, error) {
	var (
		nodes = []*LinLog{}
		_spec = llq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &LinLog{config: llq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("model: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, llq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (llq *LinLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := llq.querySpec()
	return sqlgraph.CountNodes(ctx, llq.driver, _spec)
}

func (llq *LinLogQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := llq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("model: check existence: %w", err)
	}
	return n > 0, nil
}

func (llq *LinLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   linlog.Table,
			Columns: linlog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: linlog.FieldID,
			},
		},
		From:   llq.sql,
		Unique: true,
	}
	if unique := llq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := llq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linlog.FieldID)
		for i := range fields {
			if fields[i] != linlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := llq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := llq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := llq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := llq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (llq *LinLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(llq.driver.Dialect())
	t1 := builder.Table(linlog.Table)
	columns := llq.fields
	if len(columns) == 0 {
		columns = linlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if llq.sql != nil {
		selector = llq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range llq.predicates {
		p(selector)
	}
	for _, p := range llq.order {
		p(selector)
	}
	if offset := llq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := llq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LinLogGroupBy is the group-by builder for LinLog entities.
type LinLogGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (llgb *LinLogGroupBy) Aggregate(fns ...AggregateFunc) *LinLogGroupBy {
	llgb.fns = append(llgb.fns, fns...)
	return llgb
}

// Scan applies the group-by query and scans the result into the given value.
func (llgb *LinLogGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := llgb.path(ctx)
	if err != nil {
		return err
	}
	llgb.sql = query
	return llgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (llgb *LinLogGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := llgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (llgb *LinLogGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(llgb.fields) > 1 {
		return nil, errors.New("model: LinLogGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := llgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (llgb *LinLogGroupBy) StringsX(ctx context.Context) []string {
	v, err := llgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (llgb *LinLogGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = llgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linlog.Label}
	default:
		err = fmt.Errorf("model: LinLogGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (llgb *LinLogGroupBy) StringX(ctx context.Context) string {
	v, err := llgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (llgb *LinLogGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(llgb.fields) > 1 {
		return nil, errors.New("model: LinLogGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := llgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (llgb *LinLogGroupBy) IntsX(ctx context.Context) []int {
	v, err := llgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (llgb *LinLogGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = llgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linlog.Label}
	default:
		err = fmt.Errorf("model: LinLogGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (llgb *LinLogGroupBy) IntX(ctx context.Context) int {
	v, err := llgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (llgb *LinLogGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(llgb.fields) > 1 {
		return nil, errors.New("model: LinLogGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := llgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (llgb *LinLogGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := llgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (llgb *LinLogGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = llgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linlog.Label}
	default:
		err = fmt.Errorf("model: LinLogGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (llgb *LinLogGroupBy) Float64X(ctx context.Context) float64 {
	v, err := llgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (llgb *LinLogGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(llgb.fields) > 1 {
		return nil, errors.New("model: LinLogGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := llgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (llgb *LinLogGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := llgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (llgb *LinLogGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = llgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linlog.Label}
	default:
		err = fmt.Errorf("model: LinLogGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (llgb *LinLogGroupBy) BoolX(ctx context.Context) bool {
	v, err := llgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (llgb *LinLogGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range llgb.fields {
		if !linlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := llgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := llgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (llgb *LinLogGroupBy) sqlQuery() *sql.Selector {
	selector := llgb.sql.Select()
	aggregation := make([]string, 0, len(llgb.fns))
	for _, fn := range llgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(llgb.fields)+len(llgb.fns))
		for _, f := range llgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(llgb.fields...)...)
}

// LinLogSelect is the builder for selecting fields of LinLog entities.
type LinLogSelect struct {
	*LinLogQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lls *LinLogSelect) Scan(ctx context.Context, v interface{}) error {
	if err := lls.prepareQuery(ctx); err != nil {
		return err
	}
	lls.sql = lls.LinLogQuery.sqlQuery(ctx)
	return lls.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lls *LinLogSelect) ScanX(ctx context.Context, v interface{}) {
	if err := lls.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (lls *LinLogSelect) Strings(ctx context.Context) ([]string, error) {
	if len(lls.fields) > 1 {
		return nil, errors.New("model: LinLogSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := lls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lls *LinLogSelect) StringsX(ctx context.Context) []string {
	v, err := lls.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (lls *LinLogSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lls.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linlog.Label}
	default:
		err = fmt.Errorf("model: LinLogSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lls *LinLogSelect) StringX(ctx context.Context) string {
	v, err := lls.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (lls *LinLogSelect) Ints(ctx context.Context) ([]int, error) {
	if len(lls.fields) > 1 {
		return nil, errors.New("model: LinLogSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := lls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lls *LinLogSelect) IntsX(ctx context.Context) []int {
	v, err := lls.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (lls *LinLogSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lls.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linlog.Label}
	default:
		err = fmt.Errorf("model: LinLogSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lls *LinLogSelect) IntX(ctx context.Context) int {
	v, err := lls.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (lls *LinLogSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(lls.fields) > 1 {
		return nil, errors.New("model: LinLogSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := lls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lls *LinLogSelect) Float64sX(ctx context.Context) []float64 {
	v, err := lls.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (lls *LinLogSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lls.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linlog.Label}
	default:
		err = fmt.Errorf("model: LinLogSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lls *LinLogSelect) Float64X(ctx context.Context) float64 {
	v, err := lls.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (lls *LinLogSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(lls.fields) > 1 {
		return nil, errors.New("model: LinLogSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := lls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lls *LinLogSelect) BoolsX(ctx context.Context) []bool {
	v, err := lls.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (lls *LinLogSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lls.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linlog.Label}
	default:
		err = fmt.Errorf("model: LinLogSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lls *LinLogSelect) BoolX(ctx context.Context) bool {
	v, err := lls.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lls *LinLogSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lls.sql.Query()
	if err := lls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
