// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"lin-cms-go/internal/biz"
	"lin-cms-go/internal/conf"
	"lin-cms-go/internal/data"
	"lin-cms-go/internal/server"
	"lin-cms-go/internal/service"
)

// Injectors from wire.go:

// NewWire init kratos application.
func NewWire(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	bookRepo := data.NewBookRepo(dataData, logger)
	bookUsecase := biz.NewBookUsecase(bookRepo, logger)
	linUserRepo := data.NewUserRepo(dataData, logger)
	userusecase := biz.NewUserUsecase(linUserRepo, logger)
	cmsService := service.NewCmsService(bookUsecase, userusecase)
	httpServer := server.NewHTTPServer(confServer, cmsService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
