###
POST http://localhost:3000/cms/user/login
Content-Type: application/json

{
  "username": "guest",
  "password": "123456"
}
> {% client.global.set("token", response.body.data.access_token); %}
###
POST http://localhost:3000/cms/user/register
Content-Type: application/json

{
  "username": "guest",
  "email": "guest@cms.com",
  "confirm_password": "123456",
  "group_id": 1,
  "password": "123456"
}

###
GET http://localhost:3000/cms/user/permissions
Content-Type: application/json
Authorization: Bearer {{token}}