
# @name login
POST  {{host}}/cms/user/login
Content-Type: application/json

{
  "username": "root",
  "password": "123456"
}

###
POST {{host}}/cms/user/register
Content-Type: application/json

{
  "username": "guest",
  "email": "guest@cms.com",
  "confirm_password": "123456",
  "group_id": 1,
  "password": "123456"
}
###
POST  {{host}}/cms/user/login
Content-Type: application/json

{
  "username": "guest",
  "password": "123456"
}
###

@token = {{login.response.body.$.accessToken}}

GET {{host}}/cms/admin/permissions
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{host}}/cms/admin/permissions/remove
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "group_id": 1,
  "permission_ids": [1,2]
}

###
POST {{host}}/cms/admin/permissions/dispatch
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "group_id": 1,
  "permission_ids": [1,2,3]
}
###
GET {{host}}/cms/user/permissions
Content-Type: application/json
Authorization: Bearer {{token}}
###
DELETE {{host}}/cms/admin/group/1
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{host}}/v1/book
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{host}}/v1/teacher
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{host}}/v1/teacher/1
Content-Type: application/json
Authorization: Bearer {{token}}
###
POST  {{host}}/v1/teacher
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "teacher1"

}
###
PUT {{host}}/v1/teacher/1
Content-Type: application/json
Authorization: Bearer {{token}}

{

}
###
DELETE  {{host}}/v1/teacher/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{host}}/v1/lesson
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{host}}/v1/lesson/1
Content-Type: application/json
Authorization: Bearer {{token}}
###
POST  {{host}}/v1/lesson
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "teacher1"

}
###
PUT {{host}}/v1/lesson/1
Content-Type: application/json
Authorization: Bearer {{token}}

{

}
###
DELETE  {{host}}/v1/lesson/{id}
Content-Type: application/json
Authorization: Bearer {{token}}
